name: LocaleLib
main: me.pikamug.localelib.LocaleLib
version: 1.1
api-version: 1.13
description: Show translated item/entity/etc. names in client's language
website: https://www.spigotmc.org/resources/quests.3711/
dev-url: https://github.com/PikaMug/LocaleLib
author: PikaMug